services:
  # Backend Web Service
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./todo-app/backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: todo-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: todo-db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: todo-db
          property: port
      - key: DB_SSL
        value: "true"
      - key: PORT
        value: "5000"

  # Frontend Web Service
  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./todo-app/frontend/Dockerfile
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02250373-kc5c.onrender.com

# Managed PostgreSQL database
databases:
  - name: todo-db
    plan: free
